class SportCategories {
  static const List<String> list = [
    'Football',
    'Basketball',
    'Tennis',
    'Gymnastics',
    'Swimming',
    'Running',
    'Boxing',
    'Martial Arts',
    'Cycling',
    'Skateboarding',
    'Golf',
    'Karate',
    'Surfing',
    'Athletics'
    'Cricket',
    'Baseball',
    'Rugby',
    'American Football',
    'Table Tennis',
    'Skiing',
    'Dancing',
    'Horse Riding',
    'Darts',
    'Snooker',
    'Dodgeball',
    'Netball',
    'Ice Skating',
    'Handball',
    'Squash',
    'Powerlifting',
    'Bodybuilding',
    'Badminton',
    'Volleyball',
    'Snowboarding',
    'Rock Climbing',
    'Wrestling',
    'Jujutsu',
    'Muay Thai',
    'Kickboxing',
    'F1',
    'Rally Racing',
    'Nascar',
    'Kayaking',
    'Canoeing',
    'Rowing',
    'Sailing',
    'Wakeboarding',
    'Windsurfing',
    'Water Polo',
    'CrossFit',
    'Hockey',
    'Ice Hockey',
    'Archery',
  ];
}
